// <auto-generated />
using System;
using ApiDevInCarGQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDevInCarGQL.Migrations
{
    [DbContext(typeof(DevInCarContext))]
    [Migration("20221019011100_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiDevInCarGQL.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "01101101101",
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "01181101101",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "01101901101",
                            Name = "Alfredo"
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int?>("BucketCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Chassis")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Doors")
                        .HasColumnType("int");

                    b.Property<int?>("Fuel")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int?>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = false,
                            Chassis = 0,
                            Color = "Azul",
                            Doors = 4,
                            Fuel = 1,
                            LicensePlate = "NKI9089",
                            ManufacturingDate = new DateTime(2022, 10, 18, 22, 11, 0, 136, DateTimeKind.Local).AddTicks(8171),
                            Name = "Punto",
                            Power = "260",
                            Value = 189.0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 4,
                            Available = false,
                            Chassis = 0,
                            Color = "Vermelha",
                            LicensePlate = "Npl5589",
                            ManufacturingDate = new DateTime(2022, 10, 18, 22, 11, 0, 138, DateTimeKind.Local).AddTicks(3852),
                            Name = "twister",
                            Power = "2",
                            Value = 19.0,
                            VehicleType = 2,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 2,
                            Available = false,
                            BucketCapacity = 200,
                            Chassis = 0,
                            Color = "Preto",
                            Doors = 4,
                            Fuel = 2,
                            LicensePlate = "MJE9089",
                            ManufacturingDate = new DateTime(2022, 10, 18, 22, 11, 0, 138, DateTimeKind.Local).AddTicks(4030),
                            Name = "Amarok",
                            Power = "200",
                            Value = 400.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            Available = false,
                            Chassis = 0,
                            Color = "Rosa",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "KKO9089",
                            ManufacturingDate = new DateTime(2022, 10, 18, 22, 11, 0, 138, DateTimeKind.Local).AddTicks(4234),
                            Name = "Lancer",
                            Power = "456",
                            Value = 89.0,
                            VehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
