// <auto-generated />
using System;
using ApiDevInCarGQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDevInCarGQL.Migrations
{
    [DbContext(typeof(DevInCarContext))]
    [Migration("20221016214527_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiDevInCarGQL.Models.Car", b =>
                {
                    b.Property<int>("Chassis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Chassis"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Chassis");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Chassis = 1528736604,
                            Available = true,
                            Color = "Azul",
                            Doors = 4,
                            Fuel = 1,
                            LicensePlate = "NKI9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 960, DateTimeKind.Local).AddTicks(6871),
                            Name = "Punto",
                            Power = "260",
                            Value = 189.0
                        },
                        new
                        {
                            Chassis = 1001238233,
                            Available = true,
                            Color = "Preto",
                            Doors = 2,
                            Fuel = 1,
                            LicensePlate = "LIO9007",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 964, DateTimeKind.Local).AddTicks(2376),
                            Name = "Ferrari",
                            Power = "380",
                            Value = 289.0
                        },
                        new
                        {
                            Chassis = 518802396,
                            Available = true,
                            Color = "Black",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "JUU8989",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 964, DateTimeKind.Local).AddTicks(2477),
                            Name = "Mercedez",
                            Power = "220",
                            Value = 389.0
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "01101101101",
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "01181101101",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "01101901101",
                            Name = "Alfredo"
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Moto", b =>
                {
                    b.Property<int>("Chassis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Chassis"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Chassis");

                    b.ToTable("Moto");

                    b.HasData(
                        new
                        {
                            Chassis = 677924677,
                            Available = true,
                            Color = "Azul",
                            LicensePlate = "NKI9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(1054),
                            Name = "Twister",
                            Power = "2",
                            Value = 18.0,
                            Wheels = 2
                        },
                        new
                        {
                            Chassis = 203264637,
                            Available = true,
                            Color = "Preto",
                            LicensePlate = "FGH9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(2165),
                            Name = "CG 150",
                            Power = "1.5",
                            Value = 19.0,
                            Wheels = 2
                        },
                        new
                        {
                            Chassis = 1791421939,
                            Available = true,
                            Color = "Vermelho",
                            LicensePlate = "ADB8989",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(2176),
                            Name = "Biz",
                            Power = "1.25",
                            Value = 14.0,
                            Wheels = 2
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Van", b =>
                {
                    b.Property<int>("Chassis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Chassis"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("BucketCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Chassis");

                    b.ToTable("Vans");

                    b.HasData(
                        new
                        {
                            Chassis = 576584181,
                            Available = true,
                            BucketCapacity = 400,
                            Color = "Azul",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "POI9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(6131),
                            Name = "Amarok",
                            Power = "260",
                            Value = 389.0
                        },
                        new
                        {
                            Chassis = 873609422,
                            Available = true,
                            BucketCapacity = 400,
                            Color = "Branco",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "NOI9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(7626),
                            Name = "Hylux",
                            Power = "260",
                            Value = 489.0
                        },
                        new
                        {
                            Chassis = 1297277583,
                            Available = true,
                            BucketCapacity = 400,
                            Color = "Vermelho",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "POI9089",
                            ManufacturingDate = new DateTime(2022, 10, 16, 18, 45, 25, 966, DateTimeKind.Local).AddTicks(7636),
                            Name = "S-10",
                            Power = "260",
                            Value = 289.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
