// <auto-generated />
using System;
using ApiDevInCarGQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDevInCarGQL.Migrations
{
    [DbContext(typeof(DevInCarContext))]
    partial class DevInCarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiDevInCarGQL.Models.Customer", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Cpf = "01101101101",
                            IdCustomer = 1,
                            Name = "Pedro"
                        },
                        new
                        {
                            Cpf = "01181101101",
                            IdCustomer = 2,
                            Name = "Marcia"
                        },
                        new
                        {
                            Cpf = "01101901101",
                            IdCustomer = 3,
                            Name = "Alfredo"
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Transaction", b =>
                {
                    b.Property<int?>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTransaction"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdCustomer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnName("IdVehicle");

                    b.HasKey("IdTransaction");

                    b.HasIndex("Cpf");

                    b.HasIndex("IdVehicle")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Vehicle", b =>
                {
                    b.Property<int?>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdVehicle"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int?>("BucketCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Chassis")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Doors")
                        .HasColumnType("int");

                    b.Property<int?>("Fuel")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransaction")
                        .HasColumnType("int")
                        .HasColumnName("IdTransaction");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int?>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("IdVehicle");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            IdVehicle = 1,
                            Available = true,
                            Chassis = 0,
                            Color = "Azul",
                            Doors = 4,
                            Fuel = 1,
                            LicensePlate = "NKI9089",
                            ManufacturingDate = new DateTime(2022, 10, 20, 21, 56, 44, 476, DateTimeKind.Local).AddTicks(5316),
                            Name = "Punto",
                            Power = "260",
                            Value = 189.0,
                            VehicleType = 1
                        },
                        new
                        {
                            IdVehicle = 2,
                            Available = true,
                            Chassis = 0,
                            Color = "Vermelha",
                            LicensePlate = "Npl5589",
                            ManufacturingDate = new DateTime(2022, 10, 20, 21, 56, 44, 479, DateTimeKind.Local).AddTicks(4154),
                            Name = "twister",
                            Power = "2",
                            Value = 19.0,
                            VehicleType = 2,
                            Wheels = 2
                        },
                        new
                        {
                            IdVehicle = 3,
                            Available = true,
                            BucketCapacity = 200,
                            Chassis = 0,
                            Color = "Preto",
                            Doors = 4,
                            Fuel = 2,
                            LicensePlate = "MJE9089",
                            ManufacturingDate = new DateTime(2022, 10, 20, 21, 56, 44, 479, DateTimeKind.Local).AddTicks(4503),
                            Name = "Amarok",
                            Power = "200",
                            Value = 400.0,
                            VehicleType = 0
                        },
                        new
                        {
                            IdVehicle = 4,
                            Available = true,
                            Chassis = 0,
                            Color = "Rosa",
                            Doors = 4,
                            Fuel = 0,
                            LicensePlate = "KKO9089",
                            ManufacturingDate = new DateTime(2022, 10, 20, 21, 56, 44, 479, DateTimeKind.Local).AddTicks(4792),
                            Name = "Lancer",
                            Power = "456",
                            Value = 89.0,
                            VehicleType = 1
                        });
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Transaction", b =>
                {
                    b.HasOne("ApiDevInCarGQL.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Cpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiDevInCarGQL.Models.Vehicle", "Vehicle")
                        .WithOne("transaction")
                        .HasForeignKey("ApiDevInCarGQL.Models.Transaction", "IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ApiDevInCarGQL.Models.Vehicle", b =>
                {
                    b.Navigation("transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
